version: "3.5"
services:

    # See: docker/Dockerfile
    cc18_server:
        build:
            args:
                - "DOCKER_USER=ubuntu"
                - "SERVER_TIME_ZONE=CET"

        environment:
            APACHE_RUN_USER: "ubuntu"
            APACHE_RUN_GROUP: "ubuntu"

        external_links:
            - "cc18_api_java:apijava.com"

        ports:
            - "80:80"

    # See: https://hub.docker.com/_/mysql
    cc18_mysql:
        ports: []

    # See: https://hub.docker.com/_/rabbitmq/
    cc18_rabbitmq:
        image: "rabbitmq:3"

        ports: []
